sudo: required
dist: trusty
language: shell
services:
- docker
env:
  matrix:
  - STACK=heroku-20 IMAGE_TAG=heroku/heroku:20 PRIVATE_IMAGE_TAG=heroku/heroku-private:20
script:
- bin/build.sh $STACK $IMAGE_TAG $IMAGE_TAG-build
- |
  status="$(git status --porcelain)"
  if [[ -n "$status" ]]; then
    echo -e "Regenerated files differ from checked-in versions!\n${status}\n"
    git diff --exit-code
  fi
deploy:
  - provider: script
    script: bin/convert-and-publish-to-heroku.sh
    on:
      all_branches: true
  - provider: script
    script: sh bin/publish-to-dockerhub.sh
    on:
      # Cedar-14 images must not be published to Docker Hub since they contain ESM updates.
      condition: $STACK != "cedar-14"
      all_branches: true
